name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
    - name: Install Dependencies
      run: npm i
    - name: Run Formatter
      run: npm run prettier-check
    - name: Run Linter
      run: npm run lint -- --max-warnings=0
    - name: Run Test
      run: npm test
    - name: Run Browser Test
      run: npm run test:browser
    - name: Coverage Report
      run: npm test -- --coverage && npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}